apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}-headless
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
